# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c75061744d95b46fa2ffaf08e5bbd7cb2d8d419ab4c9552f80039a46374f5b90fc1b19c1ed6475d6f5c7bc11044cca1fb3d03cbc5521d13ea51c058b4342afad

test:
  secret_key_base: 9c9e7b9c95f7c9ed8e03559155c4a3564e1cfdedfc3dc3acfb8bbac87958521cba60f561ea5d91acb0374687fe534aebcb1ed7d966eec0c757d0ae5dc4c3abf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
